
set_property OFFCHIP_TERM NONE [get_ports GPIO_SMA_J13]
set_property OFFCHIP_TERM NONE [get_ports TCM_SPI_MOSI]
set_property OFFCHIP_TERM NONE [get_ports TCM_SPI_SCK]
set_property OFFCHIP_TERM NONE [get_ports TCM_SPI_SEL]
set_property OFFCHIP_TERM NONE [get_ports LA[15]]
set_property OFFCHIP_TERM NONE [get_ports LA[14]]
set_property OFFCHIP_TERM NONE [get_ports LA[13]]
set_property OFFCHIP_TERM NONE [get_ports LA[12]]
set_property OFFCHIP_TERM NONE [get_ports LA[11]]
set_property OFFCHIP_TERM NONE [get_ports LA[10]]
set_property OFFCHIP_TERM NONE [get_ports LA[9]]
set_property OFFCHIP_TERM NONE [get_ports LA[8]]
set_property OFFCHIP_TERM NONE [get_ports LA[7]]
set_property OFFCHIP_TERM NONE [get_ports LA[6]]
set_property OFFCHIP_TERM NONE [get_ports LA[5]]
set_property OFFCHIP_TERM NONE [get_ports LA[4]]
set_property OFFCHIP_TERM NONE [get_ports LA[3]]
set_property OFFCHIP_TERM NONE [get_ports LA[2]]
set_property OFFCHIP_TERM NONE [get_ports LA[1]]
set_property OFFCHIP_TERM NONE [get_ports LA[0]]
set_property OFFCHIP_TERM NONE [get_ports sfp_rate_sel[1]]
set_property OFFCHIP_TERM NONE [get_ports sfp_rate_sel[0]]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list CDMClkpllcomp/inst/CLK_OUT1_40]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {FitGbtPrg/bc_indicator_trg_comp/bc_count[0]} {FitGbtPrg/bc_indicator_trg_comp/bc_count[1]} {FitGbtPrg/bc_indicator_trg_comp/bc_count[2]} {FitGbtPrg/bc_indicator_trg_comp/bc_count[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 12 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {FitGbtPrg/bc_indicator_trg_comp/bc_value[0]} {FitGbtPrg/bc_indicator_trg_comp/bc_value[1]} {FitGbtPrg/bc_indicator_trg_comp/bc_value[2]} {FitGbtPrg/bc_indicator_trg_comp/bc_value[3]} {FitGbtPrg/bc_indicator_trg_comp/bc_value[4]} {FitGbtPrg/bc_indicator_trg_comp/bc_value[5]} {FitGbtPrg/bc_indicator_trg_comp/bc_value[6]} {FitGbtPrg/bc_indicator_trg_comp/bc_value[7]} {FitGbtPrg/bc_indicator_trg_comp/bc_value[8]} {FitGbtPrg/bc_indicator_trg_comp/bc_value[9]} {FitGbtPrg/bc_indicator_trg_comp/bc_value[10]} {FitGbtPrg/bc_indicator_trg_comp/bc_value[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 12 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {FitGbtPrg/bc_indicator_trg_comp/bcid_in[0]} {FitGbtPrg/bc_indicator_trg_comp/bcid_in[1]} {FitGbtPrg/bc_indicator_trg_comp/bcid_in[2]} {FitGbtPrg/bc_indicator_trg_comp/bcid_in[3]} {FitGbtPrg/bc_indicator_trg_comp/bcid_in[4]} {FitGbtPrg/bc_indicator_trg_comp/bcid_in[5]} {FitGbtPrg/bc_indicator_trg_comp/bcid_in[6]} {FitGbtPrg/bc_indicator_trg_comp/bcid_in[7]} {FitGbtPrg/bc_indicator_trg_comp/bcid_in[8]} {FitGbtPrg/bc_indicator_trg_comp/bcid_in[9]} {FitGbtPrg/bc_indicator_trg_comp/bcid_in[10]} {FitGbtPrg/bc_indicator_trg_comp/bcid_in[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 6 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {FitGbtPrg/bc_indicator_trg_comp/count_sel[0]} {FitGbtPrg/bc_indicator_trg_comp/count_sel[1]} {FitGbtPrg/bc_indicator_trg_comp/count_sel[2]} {FitGbtPrg/bc_indicator_trg_comp/count_sel[3]} {FitGbtPrg/bc_indicator_trg_comp/count_sel[4]} {FitGbtPrg/bc_indicator_trg_comp/count_sel[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 6 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {FitGbtPrg/bc_indicator_trg_comp/count_tot[0]} {FitGbtPrg/bc_indicator_trg_comp/count_tot[1]} {FitGbtPrg/bc_indicator_trg_comp/count_tot[2]} {FitGbtPrg/bc_indicator_trg_comp/count_tot[3]} {FitGbtPrg/bc_indicator_trg_comp/count_tot[4]} {FitGbtPrg/bc_indicator_trg_comp/count_tot[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 80 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {FitGbtPrg/RX_Data_DataClk[0]} {FitGbtPrg/RX_Data_DataClk[1]} {FitGbtPrg/RX_Data_DataClk[2]} {FitGbtPrg/RX_Data_DataClk[3]} {FitGbtPrg/RX_Data_DataClk[4]} {FitGbtPrg/RX_Data_DataClk[5]} {FitGbtPrg/RX_Data_DataClk[6]} {FitGbtPrg/RX_Data_DataClk[7]} {FitGbtPrg/RX_Data_DataClk[8]} {FitGbtPrg/RX_Data_DataClk[9]} {FitGbtPrg/RX_Data_DataClk[10]} {FitGbtPrg/RX_Data_DataClk[11]} {FitGbtPrg/RX_Data_DataClk[12]} {FitGbtPrg/RX_Data_DataClk[13]} {FitGbtPrg/RX_Data_DataClk[14]} {FitGbtPrg/RX_Data_DataClk[15]} {FitGbtPrg/RX_Data_DataClk[16]} {FitGbtPrg/RX_Data_DataClk[17]} {FitGbtPrg/RX_Data_DataClk[18]} {FitGbtPrg/RX_Data_DataClk[19]} {FitGbtPrg/RX_Data_DataClk[20]} {FitGbtPrg/RX_Data_DataClk[21]} {FitGbtPrg/RX_Data_DataClk[22]} {FitGbtPrg/RX_Data_DataClk[23]} {FitGbtPrg/RX_Data_DataClk[24]} {FitGbtPrg/RX_Data_DataClk[25]} {FitGbtPrg/RX_Data_DataClk[26]} {FitGbtPrg/RX_Data_DataClk[27]} {FitGbtPrg/RX_Data_DataClk[28]} {FitGbtPrg/RX_Data_DataClk[29]} {FitGbtPrg/RX_Data_DataClk[30]} {FitGbtPrg/RX_Data_DataClk[31]} {FitGbtPrg/RX_Data_DataClk[32]} {FitGbtPrg/RX_Data_DataClk[33]} {FitGbtPrg/RX_Data_DataClk[34]} {FitGbtPrg/RX_Data_DataClk[35]} {FitGbtPrg/RX_Data_DataClk[36]} {FitGbtPrg/RX_Data_DataClk[37]} {FitGbtPrg/RX_Data_DataClk[38]} {FitGbtPrg/RX_Data_DataClk[39]} {FitGbtPrg/RX_Data_DataClk[40]} {FitGbtPrg/RX_Data_DataClk[41]} {FitGbtPrg/RX_Data_DataClk[42]} {FitGbtPrg/RX_Data_DataClk[43]} {FitGbtPrg/RX_Data_DataClk[44]} {FitGbtPrg/RX_Data_DataClk[45]} {FitGbtPrg/RX_Data_DataClk[46]} {FitGbtPrg/RX_Data_DataClk[47]} {FitGbtPrg/RX_Data_DataClk[48]} {FitGbtPrg/RX_Data_DataClk[49]} {FitGbtPrg/RX_Data_DataClk[50]} {FitGbtPrg/RX_Data_DataClk[51]} {FitGbtPrg/RX_Data_DataClk[52]} {FitGbtPrg/RX_Data_DataClk[53]} {FitGbtPrg/RX_Data_DataClk[54]} {FitGbtPrg/RX_Data_DataClk[55]} {FitGbtPrg/RX_Data_DataClk[56]} {FitGbtPrg/RX_Data_DataClk[57]} {FitGbtPrg/RX_Data_DataClk[58]} {FitGbtPrg/RX_Data_DataClk[59]} {FitGbtPrg/RX_Data_DataClk[60]} {FitGbtPrg/RX_Data_DataClk[61]} {FitGbtPrg/RX_Data_DataClk[62]} {FitGbtPrg/RX_Data_DataClk[63]} {FitGbtPrg/RX_Data_DataClk[64]} {FitGbtPrg/RX_Data_DataClk[65]} {FitGbtPrg/RX_Data_DataClk[66]} {FitGbtPrg/RX_Data_DataClk[67]} {FitGbtPrg/RX_Data_DataClk[68]} {FitGbtPrg/RX_Data_DataClk[69]} {FitGbtPrg/RX_Data_DataClk[70]} {FitGbtPrg/RX_Data_DataClk[71]} {FitGbtPrg/RX_Data_DataClk[72]} {FitGbtPrg/RX_Data_DataClk[73]} {FitGbtPrg/RX_Data_DataClk[74]} {FitGbtPrg/RX_Data_DataClk[75]} {FitGbtPrg/RX_Data_DataClk[76]} {FitGbtPrg/RX_Data_DataClk[77]} {FitGbtPrg/RX_Data_DataClk[78]} {FitGbtPrg/RX_Data_DataClk[79]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list FitGbtPrg/bc_indicator_trg_comp/reset]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list FitGbtPrg/bc_indicator_trg_comp/bcid_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list FitGbtPrg/RX_IsData_DataClk]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list ipbus_module/clocks/pll/inst/clkout1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 32 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {ipbus_face_comp/ctrl_reg[0][0]} {ipbus_face_comp/ctrl_reg[0][1]} {ipbus_face_comp/ctrl_reg[0][2]} {ipbus_face_comp/ctrl_reg[0][3]} {ipbus_face_comp/ctrl_reg[0][4]} {ipbus_face_comp/ctrl_reg[0][5]} {ipbus_face_comp/ctrl_reg[0][6]} {ipbus_face_comp/ctrl_reg[0][7]} {ipbus_face_comp/ctrl_reg[0][8]} {ipbus_face_comp/ctrl_reg[0][9]} {ipbus_face_comp/ctrl_reg[0][10]} {ipbus_face_comp/ctrl_reg[0][11]} {ipbus_face_comp/ctrl_reg[0][12]} {ipbus_face_comp/ctrl_reg[0][13]} {ipbus_face_comp/ctrl_reg[0][14]} {ipbus_face_comp/ctrl_reg[0][15]} {ipbus_face_comp/ctrl_reg[0][16]} {ipbus_face_comp/ctrl_reg[0][17]} {ipbus_face_comp/ctrl_reg[0][18]} {ipbus_face_comp/ctrl_reg[0][19]} {ipbus_face_comp/ctrl_reg[0][20]} {ipbus_face_comp/ctrl_reg[0][21]} {ipbus_face_comp/ctrl_reg[0][22]} {ipbus_face_comp/ctrl_reg[0][23]} {ipbus_face_comp/ctrl_reg[0][24]} {ipbus_face_comp/ctrl_reg[0][25]} {ipbus_face_comp/ctrl_reg[0][26]} {ipbus_face_comp/ctrl_reg[0][27]} {ipbus_face_comp/ctrl_reg[0][28]} {ipbus_face_comp/ctrl_reg[0][29]} {ipbus_face_comp/ctrl_reg[0][30]} {ipbus_face_comp/ctrl_reg[0][31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 32 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {ipbus_face_comp/ctrl_reg[10][0]} {ipbus_face_comp/ctrl_reg[10][1]} {ipbus_face_comp/ctrl_reg[10][2]} {ipbus_face_comp/ctrl_reg[10][3]} {ipbus_face_comp/ctrl_reg[10][4]} {ipbus_face_comp/ctrl_reg[10][5]} {ipbus_face_comp/ctrl_reg[10][6]} {ipbus_face_comp/ctrl_reg[10][7]} {ipbus_face_comp/ctrl_reg[10][8]} {ipbus_face_comp/ctrl_reg[10][9]} {ipbus_face_comp/ctrl_reg[10][10]} {ipbus_face_comp/ctrl_reg[10][11]} {ipbus_face_comp/ctrl_reg[10][12]} {ipbus_face_comp/ctrl_reg[10][13]} {ipbus_face_comp/ctrl_reg[10][14]} {ipbus_face_comp/ctrl_reg[10][15]} {ipbus_face_comp/ctrl_reg[10][16]} {ipbus_face_comp/ctrl_reg[10][17]} {ipbus_face_comp/ctrl_reg[10][18]} {ipbus_face_comp/ctrl_reg[10][19]} {ipbus_face_comp/ctrl_reg[10][20]} {ipbus_face_comp/ctrl_reg[10][21]} {ipbus_face_comp/ctrl_reg[10][22]} {ipbus_face_comp/ctrl_reg[10][23]} {ipbus_face_comp/ctrl_reg[10][24]} {ipbus_face_comp/ctrl_reg[10][25]} {ipbus_face_comp/ctrl_reg[10][26]} {ipbus_face_comp/ctrl_reg[10][27]} {ipbus_face_comp/ctrl_reg[10][28]} {ipbus_face_comp/ctrl_reg[10][29]} {ipbus_face_comp/ctrl_reg[10][30]} {ipbus_face_comp/ctrl_reg[10][31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 32 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {ipbus_face_comp/ctrl_reg[11][0]} {ipbus_face_comp/ctrl_reg[11][1]} {ipbus_face_comp/ctrl_reg[11][2]} {ipbus_face_comp/ctrl_reg[11][3]} {ipbus_face_comp/ctrl_reg[11][4]} {ipbus_face_comp/ctrl_reg[11][5]} {ipbus_face_comp/ctrl_reg[11][6]} {ipbus_face_comp/ctrl_reg[11][7]} {ipbus_face_comp/ctrl_reg[11][8]} {ipbus_face_comp/ctrl_reg[11][9]} {ipbus_face_comp/ctrl_reg[11][10]} {ipbus_face_comp/ctrl_reg[11][11]} {ipbus_face_comp/ctrl_reg[11][12]} {ipbus_face_comp/ctrl_reg[11][13]} {ipbus_face_comp/ctrl_reg[11][14]} {ipbus_face_comp/ctrl_reg[11][15]} {ipbus_face_comp/ctrl_reg[11][16]} {ipbus_face_comp/ctrl_reg[11][17]} {ipbus_face_comp/ctrl_reg[11][18]} {ipbus_face_comp/ctrl_reg[11][19]} {ipbus_face_comp/ctrl_reg[11][20]} {ipbus_face_comp/ctrl_reg[11][21]} {ipbus_face_comp/ctrl_reg[11][22]} {ipbus_face_comp/ctrl_reg[11][23]} {ipbus_face_comp/ctrl_reg[11][24]} {ipbus_face_comp/ctrl_reg[11][25]} {ipbus_face_comp/ctrl_reg[11][26]} {ipbus_face_comp/ctrl_reg[11][27]} {ipbus_face_comp/ctrl_reg[11][28]} {ipbus_face_comp/ctrl_reg[11][29]} {ipbus_face_comp/ctrl_reg[11][30]} {ipbus_face_comp/ctrl_reg[11][31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 32 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list {ipbus_face_comp/ctrl_reg[12][0]} {ipbus_face_comp/ctrl_reg[12][1]} {ipbus_face_comp/ctrl_reg[12][2]} {ipbus_face_comp/ctrl_reg[12][3]} {ipbus_face_comp/ctrl_reg[12][4]} {ipbus_face_comp/ctrl_reg[12][5]} {ipbus_face_comp/ctrl_reg[12][6]} {ipbus_face_comp/ctrl_reg[12][7]} {ipbus_face_comp/ctrl_reg[12][8]} {ipbus_face_comp/ctrl_reg[12][9]} {ipbus_face_comp/ctrl_reg[12][10]} {ipbus_face_comp/ctrl_reg[12][11]} {ipbus_face_comp/ctrl_reg[12][12]} {ipbus_face_comp/ctrl_reg[12][13]} {ipbus_face_comp/ctrl_reg[12][14]} {ipbus_face_comp/ctrl_reg[12][15]} {ipbus_face_comp/ctrl_reg[12][16]} {ipbus_face_comp/ctrl_reg[12][17]} {ipbus_face_comp/ctrl_reg[12][18]} {ipbus_face_comp/ctrl_reg[12][19]} {ipbus_face_comp/ctrl_reg[12][20]} {ipbus_face_comp/ctrl_reg[12][21]} {ipbus_face_comp/ctrl_reg[12][22]} {ipbus_face_comp/ctrl_reg[12][23]} {ipbus_face_comp/ctrl_reg[12][24]} {ipbus_face_comp/ctrl_reg[12][25]} {ipbus_face_comp/ctrl_reg[12][26]} {ipbus_face_comp/ctrl_reg[12][27]} {ipbus_face_comp/ctrl_reg[12][28]} {ipbus_face_comp/ctrl_reg[12][29]} {ipbus_face_comp/ctrl_reg[12][30]} {ipbus_face_comp/ctrl_reg[12][31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 32 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list {ipbus_face_comp/ctrl_reg[1][0]} {ipbus_face_comp/ctrl_reg[1][1]} {ipbus_face_comp/ctrl_reg[1][2]} {ipbus_face_comp/ctrl_reg[1][3]} {ipbus_face_comp/ctrl_reg[1][4]} {ipbus_face_comp/ctrl_reg[1][5]} {ipbus_face_comp/ctrl_reg[1][6]} {ipbus_face_comp/ctrl_reg[1][7]} {ipbus_face_comp/ctrl_reg[1][8]} {ipbus_face_comp/ctrl_reg[1][9]} {ipbus_face_comp/ctrl_reg[1][10]} {ipbus_face_comp/ctrl_reg[1][11]} {ipbus_face_comp/ctrl_reg[1][12]} {ipbus_face_comp/ctrl_reg[1][13]} {ipbus_face_comp/ctrl_reg[1][14]} {ipbus_face_comp/ctrl_reg[1][15]} {ipbus_face_comp/ctrl_reg[1][16]} {ipbus_face_comp/ctrl_reg[1][17]} {ipbus_face_comp/ctrl_reg[1][18]} {ipbus_face_comp/ctrl_reg[1][19]} {ipbus_face_comp/ctrl_reg[1][20]} {ipbus_face_comp/ctrl_reg[1][21]} {ipbus_face_comp/ctrl_reg[1][22]} {ipbus_face_comp/ctrl_reg[1][23]} {ipbus_face_comp/ctrl_reg[1][24]} {ipbus_face_comp/ctrl_reg[1][25]} {ipbus_face_comp/ctrl_reg[1][26]} {ipbus_face_comp/ctrl_reg[1][27]} {ipbus_face_comp/ctrl_reg[1][28]} {ipbus_face_comp/ctrl_reg[1][29]} {ipbus_face_comp/ctrl_reg[1][30]} {ipbus_face_comp/ctrl_reg[1][31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 32 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list {ipbus_face_comp/ctrl_reg[2][0]} {ipbus_face_comp/ctrl_reg[2][1]} {ipbus_face_comp/ctrl_reg[2][2]} {ipbus_face_comp/ctrl_reg[2][3]} {ipbus_face_comp/ctrl_reg[2][4]} {ipbus_face_comp/ctrl_reg[2][5]} {ipbus_face_comp/ctrl_reg[2][6]} {ipbus_face_comp/ctrl_reg[2][7]} {ipbus_face_comp/ctrl_reg[2][8]} {ipbus_face_comp/ctrl_reg[2][9]} {ipbus_face_comp/ctrl_reg[2][10]} {ipbus_face_comp/ctrl_reg[2][11]} {ipbus_face_comp/ctrl_reg[2][12]} {ipbus_face_comp/ctrl_reg[2][13]} {ipbus_face_comp/ctrl_reg[2][14]} {ipbus_face_comp/ctrl_reg[2][15]} {ipbus_face_comp/ctrl_reg[2][16]} {ipbus_face_comp/ctrl_reg[2][17]} {ipbus_face_comp/ctrl_reg[2][18]} {ipbus_face_comp/ctrl_reg[2][19]} {ipbus_face_comp/ctrl_reg[2][20]} {ipbus_face_comp/ctrl_reg[2][21]} {ipbus_face_comp/ctrl_reg[2][22]} {ipbus_face_comp/ctrl_reg[2][23]} {ipbus_face_comp/ctrl_reg[2][24]} {ipbus_face_comp/ctrl_reg[2][25]} {ipbus_face_comp/ctrl_reg[2][26]} {ipbus_face_comp/ctrl_reg[2][27]} {ipbus_face_comp/ctrl_reg[2][28]} {ipbus_face_comp/ctrl_reg[2][29]} {ipbus_face_comp/ctrl_reg[2][30]} {ipbus_face_comp/ctrl_reg[2][31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 32 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list {ipbus_face_comp/ctrl_reg[3][0]} {ipbus_face_comp/ctrl_reg[3][1]} {ipbus_face_comp/ctrl_reg[3][2]} {ipbus_face_comp/ctrl_reg[3][3]} {ipbus_face_comp/ctrl_reg[3][4]} {ipbus_face_comp/ctrl_reg[3][5]} {ipbus_face_comp/ctrl_reg[3][6]} {ipbus_face_comp/ctrl_reg[3][7]} {ipbus_face_comp/ctrl_reg[3][8]} {ipbus_face_comp/ctrl_reg[3][9]} {ipbus_face_comp/ctrl_reg[3][10]} {ipbus_face_comp/ctrl_reg[3][11]} {ipbus_face_comp/ctrl_reg[3][12]} {ipbus_face_comp/ctrl_reg[3][13]} {ipbus_face_comp/ctrl_reg[3][14]} {ipbus_face_comp/ctrl_reg[3][15]} {ipbus_face_comp/ctrl_reg[3][16]} {ipbus_face_comp/ctrl_reg[3][17]} {ipbus_face_comp/ctrl_reg[3][18]} {ipbus_face_comp/ctrl_reg[3][19]} {ipbus_face_comp/ctrl_reg[3][20]} {ipbus_face_comp/ctrl_reg[3][21]} {ipbus_face_comp/ctrl_reg[3][22]} {ipbus_face_comp/ctrl_reg[3][23]} {ipbus_face_comp/ctrl_reg[3][24]} {ipbus_face_comp/ctrl_reg[3][25]} {ipbus_face_comp/ctrl_reg[3][26]} {ipbus_face_comp/ctrl_reg[3][27]} {ipbus_face_comp/ctrl_reg[3][28]} {ipbus_face_comp/ctrl_reg[3][29]} {ipbus_face_comp/ctrl_reg[3][30]} {ipbus_face_comp/ctrl_reg[3][31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 32 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list {ipbus_face_comp/ctrl_reg[4][0]} {ipbus_face_comp/ctrl_reg[4][1]} {ipbus_face_comp/ctrl_reg[4][2]} {ipbus_face_comp/ctrl_reg[4][3]} {ipbus_face_comp/ctrl_reg[4][4]} {ipbus_face_comp/ctrl_reg[4][5]} {ipbus_face_comp/ctrl_reg[4][6]} {ipbus_face_comp/ctrl_reg[4][7]} {ipbus_face_comp/ctrl_reg[4][8]} {ipbus_face_comp/ctrl_reg[4][9]} {ipbus_face_comp/ctrl_reg[4][10]} {ipbus_face_comp/ctrl_reg[4][11]} {ipbus_face_comp/ctrl_reg[4][12]} {ipbus_face_comp/ctrl_reg[4][13]} {ipbus_face_comp/ctrl_reg[4][14]} {ipbus_face_comp/ctrl_reg[4][15]} {ipbus_face_comp/ctrl_reg[4][16]} {ipbus_face_comp/ctrl_reg[4][17]} {ipbus_face_comp/ctrl_reg[4][18]} {ipbus_face_comp/ctrl_reg[4][19]} {ipbus_face_comp/ctrl_reg[4][20]} {ipbus_face_comp/ctrl_reg[4][21]} {ipbus_face_comp/ctrl_reg[4][22]} {ipbus_face_comp/ctrl_reg[4][23]} {ipbus_face_comp/ctrl_reg[4][24]} {ipbus_face_comp/ctrl_reg[4][25]} {ipbus_face_comp/ctrl_reg[4][26]} {ipbus_face_comp/ctrl_reg[4][27]} {ipbus_face_comp/ctrl_reg[4][28]} {ipbus_face_comp/ctrl_reg[4][29]} {ipbus_face_comp/ctrl_reg[4][30]} {ipbus_face_comp/ctrl_reg[4][31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property port_width 32 [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list {ipbus_face_comp/ctrl_reg[5][0]} {ipbus_face_comp/ctrl_reg[5][1]} {ipbus_face_comp/ctrl_reg[5][2]} {ipbus_face_comp/ctrl_reg[5][3]} {ipbus_face_comp/ctrl_reg[5][4]} {ipbus_face_comp/ctrl_reg[5][5]} {ipbus_face_comp/ctrl_reg[5][6]} {ipbus_face_comp/ctrl_reg[5][7]} {ipbus_face_comp/ctrl_reg[5][8]} {ipbus_face_comp/ctrl_reg[5][9]} {ipbus_face_comp/ctrl_reg[5][10]} {ipbus_face_comp/ctrl_reg[5][11]} {ipbus_face_comp/ctrl_reg[5][12]} {ipbus_face_comp/ctrl_reg[5][13]} {ipbus_face_comp/ctrl_reg[5][14]} {ipbus_face_comp/ctrl_reg[5][15]} {ipbus_face_comp/ctrl_reg[5][16]} {ipbus_face_comp/ctrl_reg[5][17]} {ipbus_face_comp/ctrl_reg[5][18]} {ipbus_face_comp/ctrl_reg[5][19]} {ipbus_face_comp/ctrl_reg[5][20]} {ipbus_face_comp/ctrl_reg[5][21]} {ipbus_face_comp/ctrl_reg[5][22]} {ipbus_face_comp/ctrl_reg[5][23]} {ipbus_face_comp/ctrl_reg[5][24]} {ipbus_face_comp/ctrl_reg[5][25]} {ipbus_face_comp/ctrl_reg[5][26]} {ipbus_face_comp/ctrl_reg[5][27]} {ipbus_face_comp/ctrl_reg[5][28]} {ipbus_face_comp/ctrl_reg[5][29]} {ipbus_face_comp/ctrl_reg[5][30]} {ipbus_face_comp/ctrl_reg[5][31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property port_width 32 [get_debug_ports u_ila_1/probe9]
connect_debug_port u_ila_1/probe9 [get_nets [list {ipbus_face_comp/ctrl_reg[6][0]} {ipbus_face_comp/ctrl_reg[6][1]} {ipbus_face_comp/ctrl_reg[6][2]} {ipbus_face_comp/ctrl_reg[6][3]} {ipbus_face_comp/ctrl_reg[6][4]} {ipbus_face_comp/ctrl_reg[6][5]} {ipbus_face_comp/ctrl_reg[6][6]} {ipbus_face_comp/ctrl_reg[6][7]} {ipbus_face_comp/ctrl_reg[6][8]} {ipbus_face_comp/ctrl_reg[6][9]} {ipbus_face_comp/ctrl_reg[6][10]} {ipbus_face_comp/ctrl_reg[6][11]} {ipbus_face_comp/ctrl_reg[6][12]} {ipbus_face_comp/ctrl_reg[6][13]} {ipbus_face_comp/ctrl_reg[6][14]} {ipbus_face_comp/ctrl_reg[6][15]} {ipbus_face_comp/ctrl_reg[6][16]} {ipbus_face_comp/ctrl_reg[6][17]} {ipbus_face_comp/ctrl_reg[6][18]} {ipbus_face_comp/ctrl_reg[6][19]} {ipbus_face_comp/ctrl_reg[6][20]} {ipbus_face_comp/ctrl_reg[6][21]} {ipbus_face_comp/ctrl_reg[6][22]} {ipbus_face_comp/ctrl_reg[6][23]} {ipbus_face_comp/ctrl_reg[6][24]} {ipbus_face_comp/ctrl_reg[6][25]} {ipbus_face_comp/ctrl_reg[6][26]} {ipbus_face_comp/ctrl_reg[6][27]} {ipbus_face_comp/ctrl_reg[6][28]} {ipbus_face_comp/ctrl_reg[6][29]} {ipbus_face_comp/ctrl_reg[6][30]} {ipbus_face_comp/ctrl_reg[6][31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe10]
set_property port_width 32 [get_debug_ports u_ila_1/probe10]
connect_debug_port u_ila_1/probe10 [get_nets [list {ipbus_face_comp/ctrl_reg[7][0]} {ipbus_face_comp/ctrl_reg[7][1]} {ipbus_face_comp/ctrl_reg[7][2]} {ipbus_face_comp/ctrl_reg[7][3]} {ipbus_face_comp/ctrl_reg[7][4]} {ipbus_face_comp/ctrl_reg[7][5]} {ipbus_face_comp/ctrl_reg[7][6]} {ipbus_face_comp/ctrl_reg[7][7]} {ipbus_face_comp/ctrl_reg[7][8]} {ipbus_face_comp/ctrl_reg[7][9]} {ipbus_face_comp/ctrl_reg[7][10]} {ipbus_face_comp/ctrl_reg[7][11]} {ipbus_face_comp/ctrl_reg[7][12]} {ipbus_face_comp/ctrl_reg[7][13]} {ipbus_face_comp/ctrl_reg[7][14]} {ipbus_face_comp/ctrl_reg[7][15]} {ipbus_face_comp/ctrl_reg[7][16]} {ipbus_face_comp/ctrl_reg[7][17]} {ipbus_face_comp/ctrl_reg[7][18]} {ipbus_face_comp/ctrl_reg[7][19]} {ipbus_face_comp/ctrl_reg[7][20]} {ipbus_face_comp/ctrl_reg[7][21]} {ipbus_face_comp/ctrl_reg[7][22]} {ipbus_face_comp/ctrl_reg[7][23]} {ipbus_face_comp/ctrl_reg[7][24]} {ipbus_face_comp/ctrl_reg[7][25]} {ipbus_face_comp/ctrl_reg[7][26]} {ipbus_face_comp/ctrl_reg[7][27]} {ipbus_face_comp/ctrl_reg[7][28]} {ipbus_face_comp/ctrl_reg[7][29]} {ipbus_face_comp/ctrl_reg[7][30]} {ipbus_face_comp/ctrl_reg[7][31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe11]
set_property port_width 32 [get_debug_ports u_ila_1/probe11]
connect_debug_port u_ila_1/probe11 [get_nets [list {ipbus_face_comp/ctrl_reg[8][0]} {ipbus_face_comp/ctrl_reg[8][1]} {ipbus_face_comp/ctrl_reg[8][2]} {ipbus_face_comp/ctrl_reg[8][3]} {ipbus_face_comp/ctrl_reg[8][4]} {ipbus_face_comp/ctrl_reg[8][5]} {ipbus_face_comp/ctrl_reg[8][6]} {ipbus_face_comp/ctrl_reg[8][7]} {ipbus_face_comp/ctrl_reg[8][8]} {ipbus_face_comp/ctrl_reg[8][9]} {ipbus_face_comp/ctrl_reg[8][10]} {ipbus_face_comp/ctrl_reg[8][11]} {ipbus_face_comp/ctrl_reg[8][12]} {ipbus_face_comp/ctrl_reg[8][13]} {ipbus_face_comp/ctrl_reg[8][14]} {ipbus_face_comp/ctrl_reg[8][15]} {ipbus_face_comp/ctrl_reg[8][16]} {ipbus_face_comp/ctrl_reg[8][17]} {ipbus_face_comp/ctrl_reg[8][18]} {ipbus_face_comp/ctrl_reg[8][19]} {ipbus_face_comp/ctrl_reg[8][20]} {ipbus_face_comp/ctrl_reg[8][21]} {ipbus_face_comp/ctrl_reg[8][22]} {ipbus_face_comp/ctrl_reg[8][23]} {ipbus_face_comp/ctrl_reg[8][24]} {ipbus_face_comp/ctrl_reg[8][25]} {ipbus_face_comp/ctrl_reg[8][26]} {ipbus_face_comp/ctrl_reg[8][27]} {ipbus_face_comp/ctrl_reg[8][28]} {ipbus_face_comp/ctrl_reg[8][29]} {ipbus_face_comp/ctrl_reg[8][30]} {ipbus_face_comp/ctrl_reg[8][31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe12]
set_property port_width 32 [get_debug_ports u_ila_1/probe12]
connect_debug_port u_ila_1/probe12 [get_nets [list {ipbus_face_comp/ctrl_reg[9][0]} {ipbus_face_comp/ctrl_reg[9][1]} {ipbus_face_comp/ctrl_reg[9][2]} {ipbus_face_comp/ctrl_reg[9][3]} {ipbus_face_comp/ctrl_reg[9][4]} {ipbus_face_comp/ctrl_reg[9][5]} {ipbus_face_comp/ctrl_reg[9][6]} {ipbus_face_comp/ctrl_reg[9][7]} {ipbus_face_comp/ctrl_reg[9][8]} {ipbus_face_comp/ctrl_reg[9][9]} {ipbus_face_comp/ctrl_reg[9][10]} {ipbus_face_comp/ctrl_reg[9][11]} {ipbus_face_comp/ctrl_reg[9][12]} {ipbus_face_comp/ctrl_reg[9][13]} {ipbus_face_comp/ctrl_reg[9][14]} {ipbus_face_comp/ctrl_reg[9][15]} {ipbus_face_comp/ctrl_reg[9][16]} {ipbus_face_comp/ctrl_reg[9][17]} {ipbus_face_comp/ctrl_reg[9][18]} {ipbus_face_comp/ctrl_reg[9][19]} {ipbus_face_comp/ctrl_reg[9][20]} {ipbus_face_comp/ctrl_reg[9][21]} {ipbus_face_comp/ctrl_reg[9][22]} {ipbus_face_comp/ctrl_reg[9][23]} {ipbus_face_comp/ctrl_reg[9][24]} {ipbus_face_comp/ctrl_reg[9][25]} {ipbus_face_comp/ctrl_reg[9][26]} {ipbus_face_comp/ctrl_reg[9][27]} {ipbus_face_comp/ctrl_reg[9][28]} {ipbus_face_comp/ctrl_reg[9][29]} {ipbus_face_comp/ctrl_reg[9][30]} {ipbus_face_comp/ctrl_reg[9][31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe13]
set_property port_width 12 [get_debug_ports u_ila_1/probe13]
connect_debug_port u_ila_1/probe13 [get_nets [list {ipbus_face_comp/debug_ipb_addr[0]} {ipbus_face_comp/debug_ipb_addr[1]} {ipbus_face_comp/debug_ipb_addr[2]} {ipbus_face_comp/debug_ipb_addr[3]} {ipbus_face_comp/debug_ipb_addr[4]} {ipbus_face_comp/debug_ipb_addr[5]} {ipbus_face_comp/debug_ipb_addr[6]} {ipbus_face_comp/debug_ipb_addr[7]} {ipbus_face_comp/debug_ipb_addr[8]} {ipbus_face_comp/debug_ipb_addr[9]} {ipbus_face_comp/debug_ipb_addr[10]} {ipbus_face_comp/debug_ipb_addr[11]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe14]
set_property port_width 32 [get_debug_ports u_ila_1/probe14]
connect_debug_port u_ila_1/probe14 [get_nets [list {ipbus_face_comp/debug_ipb_data_I[0]} {ipbus_face_comp/debug_ipb_data_I[1]} {ipbus_face_comp/debug_ipb_data_I[2]} {ipbus_face_comp/debug_ipb_data_I[3]} {ipbus_face_comp/debug_ipb_data_I[4]} {ipbus_face_comp/debug_ipb_data_I[5]} {ipbus_face_comp/debug_ipb_data_I[6]} {ipbus_face_comp/debug_ipb_data_I[7]} {ipbus_face_comp/debug_ipb_data_I[8]} {ipbus_face_comp/debug_ipb_data_I[9]} {ipbus_face_comp/debug_ipb_data_I[10]} {ipbus_face_comp/debug_ipb_data_I[11]} {ipbus_face_comp/debug_ipb_data_I[12]} {ipbus_face_comp/debug_ipb_data_I[13]} {ipbus_face_comp/debug_ipb_data_I[14]} {ipbus_face_comp/debug_ipb_data_I[15]} {ipbus_face_comp/debug_ipb_data_I[16]} {ipbus_face_comp/debug_ipb_data_I[17]} {ipbus_face_comp/debug_ipb_data_I[18]} {ipbus_face_comp/debug_ipb_data_I[19]} {ipbus_face_comp/debug_ipb_data_I[20]} {ipbus_face_comp/debug_ipb_data_I[21]} {ipbus_face_comp/debug_ipb_data_I[22]} {ipbus_face_comp/debug_ipb_data_I[23]} {ipbus_face_comp/debug_ipb_data_I[24]} {ipbus_face_comp/debug_ipb_data_I[25]} {ipbus_face_comp/debug_ipb_data_I[26]} {ipbus_face_comp/debug_ipb_data_I[27]} {ipbus_face_comp/debug_ipb_data_I[28]} {ipbus_face_comp/debug_ipb_data_I[29]} {ipbus_face_comp/debug_ipb_data_I[30]} {ipbus_face_comp/debug_ipb_data_I[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe15]
set_property port_width 32 [get_debug_ports u_ila_1/probe15]
connect_debug_port u_ila_1/probe15 [get_nets [list {ipbus_face_comp/debug_ipb_data_O[0]} {ipbus_face_comp/debug_ipb_data_O[1]} {ipbus_face_comp/debug_ipb_data_O[2]} {ipbus_face_comp/debug_ipb_data_O[3]} {ipbus_face_comp/debug_ipb_data_O[4]} {ipbus_face_comp/debug_ipb_data_O[5]} {ipbus_face_comp/debug_ipb_data_O[6]} {ipbus_face_comp/debug_ipb_data_O[7]} {ipbus_face_comp/debug_ipb_data_O[8]} {ipbus_face_comp/debug_ipb_data_O[9]} {ipbus_face_comp/debug_ipb_data_O[10]} {ipbus_face_comp/debug_ipb_data_O[11]} {ipbus_face_comp/debug_ipb_data_O[12]} {ipbus_face_comp/debug_ipb_data_O[13]} {ipbus_face_comp/debug_ipb_data_O[14]} {ipbus_face_comp/debug_ipb_data_O[15]} {ipbus_face_comp/debug_ipb_data_O[16]} {ipbus_face_comp/debug_ipb_data_O[17]} {ipbus_face_comp/debug_ipb_data_O[18]} {ipbus_face_comp/debug_ipb_data_O[19]} {ipbus_face_comp/debug_ipb_data_O[20]} {ipbus_face_comp/debug_ipb_data_O[21]} {ipbus_face_comp/debug_ipb_data_O[22]} {ipbus_face_comp/debug_ipb_data_O[23]} {ipbus_face_comp/debug_ipb_data_O[24]} {ipbus_face_comp/debug_ipb_data_O[25]} {ipbus_face_comp/debug_ipb_data_O[26]} {ipbus_face_comp/debug_ipb_data_O[27]} {ipbus_face_comp/debug_ipb_data_O[28]} {ipbus_face_comp/debug_ipb_data_O[29]} {ipbus_face_comp/debug_ipb_data_O[30]} {ipbus_face_comp/debug_ipb_data_O[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe16]
set_property port_width 12 [get_debug_ports u_ila_1/probe16]
connect_debug_port u_ila_1/probe16 [get_nets [list {ipbus_face_comp/ipbus_addr_int[0]} {ipbus_face_comp/ipbus_addr_int[1]} {ipbus_face_comp/ipbus_addr_int[2]} {ipbus_face_comp/ipbus_addr_int[3]} {ipbus_face_comp/ipbus_addr_int[4]} {ipbus_face_comp/ipbus_addr_int[5]} {ipbus_face_comp/ipbus_addr_int[6]} {ipbus_face_comp/ipbus_addr_int[7]} {ipbus_face_comp/ipbus_addr_int[8]} {ipbus_face_comp/ipbus_addr_int[9]} {ipbus_face_comp/ipbus_addr_int[10]} {ipbus_face_comp/ipbus_addr_int[11]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe17]
set_property port_width 12 [get_debug_ports u_ila_1/probe17]
connect_debug_port u_ila_1/probe17 [get_nets [list {ipbus_face_comp/ipbus_base_addr_int[0]} {ipbus_face_comp/ipbus_base_addr_int[1]} {ipbus_face_comp/ipbus_base_addr_int[2]} {ipbus_face_comp/ipbus_base_addr_int[3]} {ipbus_face_comp/ipbus_base_addr_int[4]} {ipbus_face_comp/ipbus_base_addr_int[5]} {ipbus_face_comp/ipbus_base_addr_int[6]} {ipbus_face_comp/ipbus_base_addr_int[7]} {ipbus_face_comp/ipbus_base_addr_int[8]} {ipbus_face_comp/ipbus_base_addr_int[9]} {ipbus_face_comp/ipbus_base_addr_int[10]} {ipbus_face_comp/ipbus_base_addr_int[11]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe18]
set_property port_width 1 [get_debug_ports u_ila_1/probe18]
connect_debug_port u_ila_1/probe18 [get_nets [list ipbus_face_comp/debug_ipb_ack]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe19]
set_property port_width 1 [get_debug_ports u_ila_1/probe19]
connect_debug_port u_ila_1/probe19 [get_nets [list ipbus_face_comp/debug_ipb_isrd]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe20]
set_property port_width 1 [get_debug_ports u_ila_1/probe20]
connect_debug_port u_ila_1/probe20 [get_nets [list ipbus_face_comp/debug_ipb_iswr]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe21]
set_property port_width 1 [get_debug_ports u_ila_1/probe21]
connect_debug_port u_ila_1/probe21 [get_nets [list ipbus_face_comp/debug_ipb_rst]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list CDMClkpllcomp/inst/CLK_OUT2_320]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 4 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {FitGbtPrg/bc_indicator_data_comp/bc_count[0]} {FitGbtPrg/bc_indicator_data_comp/bc_count[1]} {FitGbtPrg/bc_indicator_data_comp/bc_count[2]} {FitGbtPrg/bc_indicator_data_comp/bc_count[3]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property port_width 12 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list {FitGbtPrg/bc_indicator_data_comp/bc_value[0]} {FitGbtPrg/bc_indicator_data_comp/bc_value[1]} {FitGbtPrg/bc_indicator_data_comp/bc_value[2]} {FitGbtPrg/bc_indicator_data_comp/bc_value[3]} {FitGbtPrg/bc_indicator_data_comp/bc_value[4]} {FitGbtPrg/bc_indicator_data_comp/bc_value[5]} {FitGbtPrg/bc_indicator_data_comp/bc_value[6]} {FitGbtPrg/bc_indicator_data_comp/bc_value[7]} {FitGbtPrg/bc_indicator_data_comp/bc_value[8]} {FitGbtPrg/bc_indicator_data_comp/bc_value[9]} {FitGbtPrg/bc_indicator_data_comp/bc_value[10]} {FitGbtPrg/bc_indicator_data_comp/bc_value[11]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property port_width 12 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list {FitGbtPrg/bc_indicator_data_comp/bcid_in[0]} {FitGbtPrg/bc_indicator_data_comp/bcid_in[1]} {FitGbtPrg/bc_indicator_data_comp/bcid_in[2]} {FitGbtPrg/bc_indicator_data_comp/bcid_in[3]} {FitGbtPrg/bc_indicator_data_comp/bcid_in[4]} {FitGbtPrg/bc_indicator_data_comp/bcid_in[5]} {FitGbtPrg/bc_indicator_data_comp/bcid_in[6]} {FitGbtPrg/bc_indicator_data_comp/bcid_in[7]} {FitGbtPrg/bc_indicator_data_comp/bcid_in[8]} {FitGbtPrg/bc_indicator_data_comp/bcid_in[9]} {FitGbtPrg/bc_indicator_data_comp/bcid_in[10]} {FitGbtPrg/bc_indicator_data_comp/bcid_in[11]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property port_width 6 [get_debug_ports u_ila_2/probe3]
connect_debug_port u_ila_2/probe3 [get_nets [list {FitGbtPrg/bc_indicator_data_comp/count_sel_1[0]} {FitGbtPrg/bc_indicator_data_comp/count_sel_1[1]} {FitGbtPrg/bc_indicator_data_comp/count_sel_1[2]} {FitGbtPrg/bc_indicator_data_comp/count_sel_1[3]} {FitGbtPrg/bc_indicator_data_comp/count_sel_1[4]} {FitGbtPrg/bc_indicator_data_comp/count_sel_1[5]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe4]
set_property port_width 6 [get_debug_ports u_ila_2/probe4]
connect_debug_port u_ila_2/probe4 [get_nets [list {FitGbtPrg/bc_indicator_data_comp/count_tot_0[0]} {FitGbtPrg/bc_indicator_data_comp/count_tot_0[1]} {FitGbtPrg/bc_indicator_data_comp/count_tot_0[2]} {FitGbtPrg/bc_indicator_data_comp/count_tot_0[3]} {FitGbtPrg/bc_indicator_data_comp/count_tot_0[4]} {FitGbtPrg/bc_indicator_data_comp/count_tot_0[5]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe5]
set_property port_width 1 [get_debug_ports u_ila_2/probe5]
connect_debug_port u_ila_2/probe5 [get_nets [list FitGbtPrg/bc_indicator_data_comp/bcid_en]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe6]
set_property port_width 1 [get_debug_ports u_ila_2/probe6]
connect_debug_port u_ila_2/probe6 [get_nets [list FitGbtPrg/bc_indicator_data_comp/reset]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets CDM_pll_SysClk]
